version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: mypostgres
    build:
      context: .
      dockerfile: DockerfilePostgres
    volumes:
      - django_data_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rest_api:
    build:
      context: .
      dockerfile: DockerfilePython
    container_name: mydjangorestapi
    command: ./run-migrate-and-server.sh
    volumes:
      - ./code/django_rest_api:/code
    ports:
      - "8000:8000"
    depends_on:
      - database

  web_front:
    build:
      context: .
      dockerfile: DockerfileNode
    container_name: mydjangowebfront
    command: ./npm-install-and-start.sh
    volumes:
      - ./code/django_web_front:/code
    ports:
      - "3000:3000"
    depends_on:
      - rest_api

volumes:
  django_data_volume:
