version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: mypostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_app
    ports:
      - "5432:5432"

  rest_api:
    build:
      context: .
      dockerfile: docker/run.Dockerfile
      cache_from:
        - system
        - build
        - app
    container_name: mydjangorestapi
    ports:
      - "8000:8000"
    depends_on:
      - database

  web_front:
    build:
      context: .
      dockerfile: docker/run.Dockerfile
      cache_from:
        - system
        - build
        - app
    container_name: mydjangowebfront
    command:  ["sh", "./npm-install-and-start.sh"]
    volumes:
      - ./code/django_web_front:/code
    ports:
      - "3001:3000"
    depends_on:
      - database
volumes:
  django_data_volume: