# путь к файлу логов ошибок
error_log /var/log/nginx/error.log;

# количество рабочих процессов
worker_processes 1;

# обработка подключений, каждый воркер может обслуживать до 1024 одновременных соединений
events {
    worker_connections 1024;
}

# правила обработки HTTP-запросов
http {
# объявление HTTP серверов
    server {
    # NGINX будет слушать порт 3000
        listen 3000;

    # обрабатываются запросы на корень и все остальные пути
        location / {
            # каталог, откуда NGINX будет отдавать файлы
            root /usr/share/nginx/html;
            # файл, который нужно считать "главной страницей"
            index index.html;
            # попытаться отдать файл по пути $uri, а если такого файла нет — вернуть index.html
            try_files $uri /index.html;
        }
    }
}