# путь к файлу логов ошибок
error_log /var/log/nginx/error.log;

# количество рабочих процессов
worker_processes 1;

# обработка подключений, каждый воркер может обслуживать до 1024 одновременных соединений
events {
    worker_connections 1024;
}

# правила обработки HTTP-запросов
http {
    # создание группы серверов для направления запросов к фронту
    upstream frontend {
        # имя сервиса из docker-compose, подключение к его 3000 порту (React-приложение)
        server frontend:3000;
    }

    # создание группы серверов для направления запросов к бэку
    upstream backend {
        # имя сервиса Spring Boot-приложения в Docker, слушающего на 8080 порту
        server backend:8080;
    }

# объявление HTTP серверов
    server {
    # NGINX будет слушать порт 3000
        listen 3000;

        # все запросы на "/" будут отправляться в группу frontend
        location / {
            proxy_pass http://frontend;
        }

        # все запросы, начинающиеся с "/api", будут перенаправлены в группу backend
        location /api {
            proxy_pass http://backend;
        }
    }
}